### ISSUE TITLE
Does not work with ForeignKeys in Django 1.9

### ISSUE THREAD

**Issue by Bakirelived** [LegoStormtroopr/django-spaghetti-and-meatballs#8]
when trying to create views for apps that have models with ForignKey, it raises an error:

```
Traceback (most recent call last):
  File "/home/msilva/.virtualenvs/django1.9/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/msilva/.virtualenvs/django1.9/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/msilva/.virtualenvs/django1.9/local/lib/python2.7/site-packages/django_spaghetti/views.py", line 35, in plate
    _to = tuple(str(f.related_field).lower().split('.')[0:2])
AttributeError: 'ForeignKey' object has no attribute 'related_field'
```

**Comment by LegoStormtroopr** [comment]
Ah-ha. Django 1.9 Strikes again!
Hopefully for such a small app, this is a simple fix...

**Comment by LegoStormtroopr** [comment]
Thanks for the pick up.
Code is much cleaner now. Dropped support for 1.7.
Master should be all caught up, will release a new version soon.

**Comment by Bakirelived** [comment]
ty, i didnt fount the problem as i was in a hurry, but thanks for being so fast
